name: CI
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  jvm:
    strategy:
      fail-fast: false
      matrix:
        java: [11, 8]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v10
      - run: sbt test