name: CI
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  jvm:
    strategy:
      fail-fast: false
      matrix:
        java: [8, 11, 16]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v10
        with:
          java-version: "adopt@1.${{ matrix.java }}"
      - run: sbt test